### ISSUE TITLE
Bookmark Toolbar

### ISSUE THREAD

**Issue by MudkipBanana** [PROxZIMA/Firefox-Theme#1]
Is there a way to show the bookmark toolbar on another line? I absolutely love this theme, but not having quick access to bookmarks is a bit of a killer.

**Comment by PROxZIMA** [comment]
@MudkipBanana I tried adding `Bookmarks Toolbar` but it was breaking `Navigation Toolbar` :( By the time I manage to get this done, you can either use `Ctrl + B` or a `New Tab page` to access your bookmarks.

**Comment by PROxZIMA** [comment]
There were few bugs due to bookmarks toolbar. Fixed now!!!!
