### ISSUE TITLE
Hide Scrollbars doesn't work as of Firefox 89.0.1

### ISSUE THREAD

**Issue by ninryu** [PROxZIMA/Firefox-Theme#3]

**Comment by PROxZIMA** [comment]
In `about:config` search for `userChromeJS.scriptsDisabled`. Edit it and remove `hideScrollbar.uc.js` from there. Restart to enable scrollbars.
I've re-added some user pref in `hideScrollbar.uc.js` to enable/disable it manually.

**Comment by ninryu** [comment]
I think you misunderstood, I want the scrollbars to be hidden.

**Comment by PROxZIMA** [comment]
Ahh sorry. If you want to completely disable scrollbars then add
```
scrollbar {
    display: none !important;
}
```
to `hideScrollbar.uc.js` after line 133 (at end of `css` variable)

**Comment by ninryu** [comment]
Thank you.

**Comment by DMITROSE** [comment]
> 
> 
> В `about:config`ищи `userChromeJS.scriptsDisabled`. Отредактируйте и удалите `hideScrollbar.uc.js`оттуда. Перезагрузите, чтобы включить полосы прокрутки.
> Я повторно добавил пользовательскую настройку в `hideScrollbar.uc.js`для включения / отключения вручную.
> Вы также можете проверить, загружен ли скрипт или нет, в строке меню> Инструменты> userScripts> *. Отключите их, щелкнув по ним, и они будут добавлены в `userChromeJS.scriptsDisabled`предпочтение.
> 
> [https://github.com/PROxZIMA/Firefox-Theme/blob/f494b71d8b1b6ce4869edacb7ae9584441ea081e/README.md#L157 ](https://github.com/PROxZIMA/Firefox-Theme/blob/f494b71d8b1b6ce4869edacb7ae9584441ea081e/README.md#L157)

I have updated to version 2.0.0 according to the new manual, success was no longer a problem, as described in this [post](https://www.reddit.com/r/FirefoxCSS/comments/pc7w2t/minor_bugs_appeared_on_the_installed_theme/). But the auto-hide of the scrollbar no longer works for me.
I decided to apply the method as described here, but nothing helped, I made a new profile, but there was also no successful result.
